### ISSUE TITLE
List of 100Devs community projects to contribute on

### ISSUE THREAD

**Issue by nmpereira** [labrocadabro/communitytaught#57]
In the resources section, we can add a section where one could go and find 100Dev community projects to use, and to contribute to.

For example, the together app (https://github.com/Together-100Devs/Together) and communityFocus (https://github.com/CommunityFocus) are both community projects built by and for 100devs. 

It would be really nice to have a centralized location where one could go and see these projects.

Note: These projects should be defined in code (GitHub), so the only way a project maintainer can add their project to this list is via a pull request that can be vetted and approved.

**Comment by labrocadabro** [comment]
I agree, it's a great idea to have a single spot to find such projects. It _might_ be more appropriate for the main site (I'm not sure what the plans are exactly there, so I could be wrong). Happy to put something up here, at least for now. If it's just the two projects for now, it might be better to add an FAQ entry for it rather than a dedicated page. 

If you've got something particular in mind, let me know.

**Comment by nmpereira** [comment]
Already added a little something in a PR https://github.com/labrocadabro/communitytaught/pull/59

Let me know here what you think about the implementation.

**Comment by labrocadabro** [comment]
Looks good. I'll be reviewing PRs and merging tomorrow, will take a closer look then.
