### ISSUE TITLE
Support for video contents with corresponding timestamps

### ISSUE THREAD

**Issue by nmpereira** [labrocadabro/communitytaught#60]
Depends on https://github.com/labrocadabro/communitytaught/issues/58

Once the above issue is closed, a feature to tag video timestamps to the corresponding topics discussed would be great.

For example:
2:00 introduction
5:00 flexbox
10:00 flexbox froggy
1:10:15 Intro to js

Clicking on the above would route to https://communitytaught.org/class/learn-html?t=2m or so

Clarification: This is completely independent of tags in https://github.com/labrocadabro/communitytaught/issues/27. #27 is to filter lessons based on the tag. This feature will be in any given lesson with the topics discussed in them.

**Comment by labrocadabro** [comment]
So as far as the actual data for tagging goes, I'd like to keep it to 5-ish per video (10 at the outside), giving more of a general overview of the topics covered. I think transcript search plus a feature I've been planning to implement since I made the site - timestamp "chapters" on each video page - will cover the more specific cases.

What you've mentioned above is more like the chapter feature, I'm spinning that out into a different issue (which I suspect you'll have finished before I wake up tomorrow 😆). 

It may still be useful to link tags to specific timestamps, that's something we can discuss and implement in a different issue if it seems worthwhile.

**Comment by nmpereira** [comment]
I believe https://github.com/labrocadabro/communitytaught/issues/61 is a duplicate of this. I added more clarification but what I intended to add was the chapters features. The tags from #27 is completely independent of this feature

**Comment by labrocadabro** [comment]
Discussion moved to #61.
